# This is a basic workflow to help you get started with Actions

name: Post JSON File to Four URLs

on:
  push:
    branches:
      - main # Runs only when pushing to the main branch
  workflow_dispatch: # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:HxPpL3GGRBeJWb5E3bx0XA@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:GkmeWxvfQuiiJ1tcNz09RQ/streams/AQAAAGN7ULvAekdgriN2vvr4PGYAAAAA" \
          -H "Content-Type: application/json" \
          -d @stream.json

      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:Eqvs9__2Qxq2R6Js4Q3KGw@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:GkmeWxvfQuiiJ1tcNz09RQ/streams/AQAAANq_WQWdkkrRsuhJSOoawX4AAAAA" \
          -H "Content-Type: application/json" \
          -d @stream.json

      - name: Send JSON Data to Third URL
        run: |
          curl -X POST "https://:aXenUdNDRzSciPYol_S2hA@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:GkmeWxvfQuiiJ1tcNz09RQ/streams/AQAAAPYj1bDpJ0Elio1dcsaiE_sAAAAA" \
          -H "Content-Type: application/json" \
          -d @stream.json

      - name: Send JSON Data to Fourth URL
        run: |
          curl -X POST "https://:XJQ7eTKVQVWEhb_9YQNUTA@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:GkmeWxvfQuiiJ1tcNz09RQ/streams/AQAAADzpB6_3uU-grS34kbgFtzsAAAAA" \
          -H "Content-Type: application/json" \
          -d @stream.json

