# This is a basic workflow to help you get started with Actions

name: Post JSON File to Two URLs 

 

on: 
  push: 
    branches: 
      - main  # Runs only when pushing to the main branch 
  workflow_dispatch:  # Allows manual trigger 

 

jobs: 
  post_json: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Repository 
        uses: actions/checkout@v3 

 

      - name: Send JSON Data to First URL 
        run: | 
          curl -X POST "https://first-api-url.com" \ 
               -H "Content-Type: application/json" \ 
               -d @stream.json 

 

      - name: Send JSON Data to Second URL 
        run: | 
          curl -X POST "https://second-api-url.com" \ 
               -H "Content-Type: application/json" \ 
               -d @stream.json 
               
      - name: Send JSON Data to Third URL 
        run: | 
          curl -X POST "https://third-api-url.com" \ 
               -H "Content-Type: application/json" \ 
               -d @stream.json 

 

      - name: Send JSON Data to Fourth URL 
        run: | 
          curl -X POST "https://fourth-api-url.com" \ 
               -H "Content-Type: application/json" \ 
               -d @stream.json 
